name: AdversarialMapGeneration
channels:
- pytorch
- defaults
dependencies:
- python=3.7
- pytorch=1.11.0
- scipy
- pip
- pip:
  - dominate==2.4.0
  - torchvision==0.12.0
  - Pillow==6.1.0
  - numpy==1.16.4
  - visdom==0.1.8
  - scikit-image
  - shapely
  - matplotlib
